-- Link điểm danh / đăng ký nhận tool cho tubekey.vn.
-- Chạy một lần trong Supabase SQL Editor trước khi dùng màn hình quản trị.

create table if not exists public.tool_intake_campaigns (
  id bigint generated by default as identity primary key,
  name varchar(150) not null,
  slug varchar(80) not null unique,
  title varchar(200) not null,
  description text not null default '',
  success_message varchar(1000) not null default 'Đăng ký thành công. Hệ thống đã tiếp nhận thông tin của bạn.',
  tool_url text not null default '',
  delivery_mode varchar(20) not null default 'manual' check (delivery_mode in ('manual','show_link','email_link')),
  email_subject varchar(300) not null default 'Link nhận tool - {{campaign}}',
  email_html text not null default '',
  button_label varchar(80) not null default 'Đăng ký nhận tool',
  require_phone boolean not null default true,
  require_zalo boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tool_intake_entries (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.tool_intake_campaigns(id) on delete cascade,
  full_name varchar(150) not null,
  email varchar(190) not null,
  phone varchar(30) not null default '',
  zalo varchar(200) not null default '',
  use_case text not null default '',
  status varchar(20) not null default 'new' check (status in ('new','granted','sent','rejected')),
  linked_uid varchar(160) not null default '',
  grant_message varchar(500) not null default '',
  email_status varchar(20) not null default 'not_sent' check (email_status in ('not_sent','sent','failed')),
  email_error varchar(1000) not null default '',
  ip_hash varchar(64) not null default '',
  user_agent varchar(500) not null default '',
  granted_at timestamptz,
  email_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists tool_intake_entries_campaign_email_uq
  on public.tool_intake_entries (campaign_id, lower(email));
create index if not exists tool_intake_entries_campaign_created_idx
  on public.tool_intake_entries (campaign_id, created_at desc);
create index if not exists tool_intake_entries_status_idx
  on public.tool_intake_entries (status, email_status);

create table if not exists public.tool_intake_email_logs (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.tool_intake_campaigns(id) on delete cascade,
  entry_id bigint references public.tool_intake_entries(id) on delete set null,
  to_email varchar(190) not null,
  subject varchar(300) not null default '',
  status varchar(20) not null check (status in ('sent','failed')),
  error_message varchar(1000) not null default '',
  created_at timestamptz not null default now()
);

create index if not exists tool_intake_email_logs_campaign_created_idx
  on public.tool_intake_email_logs (campaign_id, created_at desc);

alter table public.tool_intake_campaigns enable row level security;
alter table public.tool_intake_entries enable row level security;
alter table public.tool_intake_email_logs enable row level security;

revoke all on table public.tool_intake_campaigns from anon, authenticated;
revoke all on table public.tool_intake_entries from anon, authenticated;
revoke all on table public.tool_intake_email_logs from anon, authenticated;

grant select, insert, update, delete on table public.tool_intake_campaigns to service_role;
grant select, insert, update, delete on table public.tool_intake_entries to service_role;
grant select, insert, update, delete on table public.tool_intake_email_logs to service_role;
grant usage, select on sequence public.tool_intake_campaigns_id_seq to service_role;
grant usage, select on sequence public.tool_intake_entries_id_seq to service_role;
grant usage, select on sequence public.tool_intake_email_logs_id_seq to service_role;

