-- Link đăng ký nâng cấp PRO cho tubekey.vn.
-- Chạy một lần trong Supabase SQL Editor trước khi dùng màn hình quản trị.
-- Tương thích với schema intake cũ: giữ nguyên bảng cũ dưới tên
-- tool_intake_entries_legacy_v86 rồi tạo bảng mới mà API hiện tại cần.

begin;

do $$
begin
  if to_regclass('public.tool_intake_entries') is not null
     and not exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'tool_intake_entries'
         and column_name = 'campaign_id'
     ) then
    if to_regclass('public.tool_intake_entries_legacy_v86') is null then
      alter table public.tool_intake_entries rename to tool_intake_entries_legacy_v86;
    else
      raise exception 'Không thể nâng cấp: tool_intake_entries_legacy_v86 đã tồn tại.';
    end if;
  end if;
end $$;

create table if not exists public.tool_intake_campaigns (
  id bigint generated by default as identity primary key,
  name varchar(150) not null,
  slug varchar(80) not null unique,
  title varchar(200) not null,
  description text not null default '',
  success_message varchar(1000) not null default 'Đã tiếp nhận thông tin. Admin sẽ kiểm tra và nâng cấp tài khoản PRO.',
  tool_url text not null default '',
  delivery_mode varchar(20) not null default 'manual' check (delivery_mode in ('manual','show_link','email_link')),
  email_subject varchar(300) not null default 'Link nhận tool - {{campaign}}',
  email_html text not null default '',
  button_label varchar(80) not null default 'Đăng ký nâng cấp PRO',
  require_phone boolean not null default true,
  require_zalo boolean not null default true,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tool_intake_entries (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.tool_intake_campaigns(id) on delete cascade,
  full_name varchar(150) not null,
  email varchar(190) not null,
  phone varchar(30) not null default '',
  zalo varchar(200) not null default '',
  use_case text not null default '',
  status varchar(20) not null default 'new' check (status in ('new','granted','sent','rejected')),
  linked_uid varchar(160) not null default '',
  grant_message varchar(500) not null default '',
  email_status varchar(20) not null default 'not_sent' check (email_status in ('not_sent','sent','failed')),
  email_error varchar(1000) not null default '',
  ip_hash varchar(64) not null default '',
  user_agent varchar(500) not null default '',
  granted_at timestamptz,
  email_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists tool_intake_entries_campaign_email_uq
  on public.tool_intake_entries (campaign_id, lower(email));
create unique index if not exists tool_intake_entries_campaign_phone_uq
  on public.tool_intake_entries (campaign_id, phone);
create index if not exists tool_intake_entries_campaign_created_idx
  on public.tool_intake_entries (campaign_id, created_at desc);
create index if not exists tool_intake_entries_status_idx
  on public.tool_intake_entries (status, email_status);

-- Đồng bộ bản cài cũ sang luồng nâng cấp PRO và bắt buộc đủ thông tin.
alter table public.tool_intake_campaigns
  alter column success_message set default 'Đã tiếp nhận thông tin. Admin sẽ kiểm tra và nâng cấp tài khoản PRO.',
  alter column button_label set default 'Đăng ký nâng cấp PRO',
  alter column require_phone set default true,
  alter column require_zalo set default true;

update public.tool_intake_campaigns
set button_label = 'Đăng ký nâng cấp PRO',
    require_phone = true,
    require_zalo = true,
    delivery_mode = 'manual',
    tool_url = '',
    description = case
      when btrim(coalesce(description, '')) = '' then 'Điền đúng số điện thoại, email và link nhóm Zalo để admin kiểm tra.'
      else description
    end,
    success_message = case
      when btrim(coalesce(success_message, '')) = ''
        or success_message = 'Đăng ký thành công. Hệ thống đã tiếp nhận thông tin của bạn.'
      then 'Đã tiếp nhận thông tin. Admin sẽ kiểm tra và nâng cấp tài khoản PRO.'
      else success_message
    end,
    updated_at = now();

alter table public.tool_intake_entries
  drop constraint if exists tool_intake_entries_email_format_ck,
  drop constraint if exists tool_intake_entries_email_domain_typo_ck;

alter table public.tool_intake_entries
  add constraint tool_intake_entries_email_format_ck check (
    length(email) between 6 and 190
    and email ~* '^[A-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?(?:[.][A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?)+$'
    and split_part(email, '@', 1) !~ '^[.]|[.]$'
    and position('..' in email) = 0
    and reverse(split_part(reverse(split_part(email, '@', 2)), '.', 1)) ~* '^(?:[A-Z]{2,63}|XN--[A-Z0-9-]{2,59})$'
  ),
  add constraint tool_intake_entries_email_domain_typo_ck check (
    lower(split_part(email, '@', 2)) not in (
      'gmai.com','gmial.com','gmail.co','gmail.con','gmail.cm','gmail.om',
      'googlemai.com','googlemail.co','outlok.com','outlook.co','outlook.con',
      'hotmai.com','hotmal.com','hotmail.co','hotmail.con','yaho.com','yhoo.com',
      'yahoo.co','yahoo.con','icloud.co','icloud.con','iclod.com'
    )
  );

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'tool_intake_entries_phone_vn_ck') then
    alter table public.tool_intake_entries
      add constraint tool_intake_entries_phone_vn_ck
      check (phone ~ '^0(3[2-9]|5[2689]|7[06-9]|8[1-9]|9[0-46-9])[0-9]{7}$');
  end if;
  if not exists (select 1 from pg_constraint where conname = 'tool_intake_entries_zalo_group_ck') then
    alter table public.tool_intake_entries
      add constraint tool_intake_entries_zalo_group_ck
      check (zalo ~ '^https://zalo[.]me/g/[A-Za-z0-9_-]{8,80}$');
  end if;
end $$;

create table if not exists public.tool_intake_email_logs (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.tool_intake_campaigns(id) on delete cascade,
  entry_id bigint references public.tool_intake_entries(id) on delete set null,
  to_email varchar(190) not null,
  subject varchar(300) not null default '',
  status varchar(20) not null check (status in ('sent','failed')),
  error_message varchar(1000) not null default '',
  created_at timestamptz not null default now()
);

create index if not exists tool_intake_email_logs_campaign_created_idx
  on public.tool_intake_email_logs (campaign_id, created_at desc);
create index if not exists tool_intake_email_logs_entry_idx
  on public.tool_intake_email_logs (entry_id);

alter table public.tool_intake_campaigns enable row level security;
alter table public.tool_intake_entries enable row level security;
alter table public.tool_intake_email_logs enable row level security;

revoke all on table public.tool_intake_campaigns from anon, authenticated;
revoke all on table public.tool_intake_entries from anon, authenticated;
revoke all on table public.tool_intake_email_logs from anon, authenticated;

grant select, insert, update, delete on table public.tool_intake_campaigns to service_role;
grant select, insert, update, delete on table public.tool_intake_entries to service_role;
grant select, insert, update, delete on table public.tool_intake_email_logs to service_role;
grant usage, select on sequence public.tool_intake_campaigns_id_seq to service_role;
grant usage, select on sequence public.tool_intake_entries_id_seq to service_role;
grant usage, select on sequence public.tool_intake_email_logs_id_seq to service_role;

revoke all on sequence public.tool_intake_campaigns_id_seq from anon, authenticated;
revoke all on sequence public.tool_intake_entries_id_seq from anon, authenticated;
revoke all on sequence public.tool_intake_email_logs_id_seq from anon, authenticated;

commit;
